### PR TITLE
[WIP]: adds swedish translation

### PR DESCRIPTION
**Pull request by sphrak**
hey mate,
This adds swedish translation, but I need to investigate a few things before this can be merged.

### CODE REVIEW

**Comment by MFlisar** [comment]
thanks, just let me know when it's finished

**Comment by sphrak** [comment]
@MFlisar signoff, its ready to be merged :)

**Comment by MFlisar** [comment]
thanks

**Comment by johny2000uwb** [comment]
Could you create the release with this new Language?

**Comment by johny2000uwb** [comment]
Thank you

**Comment by MFlisar** [comment]
Done. Btw, you can always use ANY commit as well, like following:

    // snapshot of current branch
    implementation 'com.github.MFlisar:GDPRDialog:-SNAPSHOT'  // always the latest
    // use a commit tag
    implementation 'com.github.MFlisar:GDPRDialog:246c2dbcc1'

Commit tags can be found here e.g.: https://github.com/MFlisar/GDPRDialog/commits/master

**Comment by johny2000uwb** [comment]
Ok, thank you. Good point. I will notice it.

**Pull request merged**
