### PR TITLE
Updated Czech translation

### PR DESCRIPTION
**Pull request by thubalek**
Updated Czech translation
Moved non translatable strings into donottranslate.xml file
Updated demo app

### CODE REVIEW

**Comment by MFlisar** [comment]
the `gdpr_dialog_question` string needs a `%1$s` part. This part will be replaced with an empty string if no ad network is used or with `gdpr_dialog_question_ads_info` otherwise.

**Comment by MFlisar** [comment]
After merging I'll add following comments to the english resources, hopefully this helps:

```XML
<!-- %1$s is replaced with a 'gdpr_dialog_question_ads_info' string if the setup contains an ad network, otherwise with an empty string -->
<string name="gdpr_dialog_question">Can we continue to use your data for these purposes%1$s?</string>
<string name="gdpr_dialog_question_ads_info">\u0020as well as for showing personalized ads</string>
```

**Comment by thubalek** [comment]
Should be fixed now.

**Comment by MFlisar** [comment]
great, thank you very much

**Pull request merged**
