### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by thubalek**
I translated English texts to Czech. It is not exact (1:1) translation I prefered to sentences that make sense to Czech users.

### CODE REVIEW

**Comment by MFlisar** [comment]
Thanks a lot. Please check out `gdpr_dialog_question` and `gdpr_dialog_question_ads_info` again as I just changed them

**Comment by MFlisar** [comment]
@thubalek 

maybe you have not seen my comment, please check it; otherwise I will remove the two resources from the czech translation and the english fallback will be used for now. No big problem, can be changed at anytime again...

**Comment by MFlisar** [comment]
I've already merged it, simply open a new one please when your done. Thanks

**Comment by thubalek** [comment]
Ok, I'll do.

Dne čt 24. 5. 2018 7:26 uživatel MFlisar <notifications@github.com> napsal:

**Pull request merged**
